Draft: createISTPattrs needed documentation and testing
spacepy/spacepy pull request #438
Opened 2020-11-06 21:54 UTC by balarsen

- [X ] Pull request has descriptive title
- [ X] Pull request gives overview of changes
- [ X] New code has inline comments where necessary
- [ X fixed] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [ X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ X fixed ] New features and bug fixes should have unit tests
- [ X ] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

This is related to #305, `createISTPattrs` needed else handler for datatype. Documentation was added and unittests, really regression tests as this is a "factory" function

2020-11-06 21:55 UTC, balarsen commented
@jtniehof please look both at the code updates but also that the returned meatadata is compete. Mayeb this should move to `pycdf/istp.py`

2020-11-06 21:56 UTC, balarsen commented
Actually hang off. It somehow grabbed other changes in a different branch

2020-11-06 22:03 UTC, balarsen commented
Ok, offending commits removed, this is good for review, @jtniehof

2020-11-13 16:20 UTC, jtniehof requested changes
Long-term I agree this should be pulled into other ISTP handling, but this is nice for now.

Good except typos and such. There are some other things in the numpydoc guide regarding labeling optional stuff; I think it would make more sense to modify this commit or make a patch-up commit rather than trying to apply the suggestions (I think we've had problems with multi-line suggestions in the past.) That would then be an opportunity to apply the optional label per the numpydoc.

2020-11-13 16:20 UTC, jtniehof commented on CHANGELOG
> + - Documentation update and default untis change in createISTPattrs
```suggestion
 - Documentation update and default units change in createISTPattrs
```

2020-11-13 16:20 UTC, jtniehof commented on spacepy/datamodel.py
> +        datatype of variable to reate metadata for (data|support_data|metadata)
```suggestion
    datatype : {'data', 'support_data', 'metadata'}
        datatype of variable to create metadata for.
```

See "parameters" in the [numpydoc docs](https://numpydoc.readthedocs.io/en/latest/format.html#sections)

2020-11-13 16:20 UTC, jtniehof commented on spacepy/datamodel.py
> +        The type of the variable (float|char|int|epoch|tt2000), default=float
```suggestion
    vartype : {'float', 'char', 'int', 'epoch', 'tt2000'}
        The type of the variable, default=float
```

2020-11-16 18:43 UTC, jtniehof commented
Yikes, those are non-descriptive commit messages...is that what you get when you accept the suggestion in the PR review?

2020-11-16 19:14 UTC, balarsen commented
> 
> 
> Yikes, those are non-descriptive commit messages...is that what you get when you accept the suggestion in the PR review?

I guess so, I never saw any messages go by... any ideas on how to modify them?

2020-11-16 19:21 UTC, balarsen commented
I cleaned those up, followed https://www.educative.io/edpresso/how-to-change-a-git-commit-message-after-a-push and used `git rebase -i HEAD~3` pretty cool interactive functionality

2020-11-16 19:25 UTC, jtniehof commented
Yep, rebase is awesome, makes new commits so have to force push, as you noticed.

2020-11-18 18:25 UTC, jtniehof approved these changes
Looks good here. Thanks.

2020-11-18 18:26 UTC, merged