PEP 517/518 support for install numpy before build
spacepy/spacepy pull request #517
Opened 2021-03-12 22:46 UTC by jtniehof

Newer versions of pip support installing build dependencies before trying the build, so for instance people don't need to install numpy before installing SpacePy from source via pip. This is a re-open/extension of #440, which got erroneously closed by GitHub being overzealous about the definition of "merged." See discussion there for details.

2021-03-12 22:48 UTC, jtniehof commented
This can be tested with `pip install git+https://github.com/jtniehof/spacepy/@pep518`, making sure `numpy` isn't installed first. See more discussion of fun things to try in #440 .

2021-03-19 21:04 UTC, balarsen approved these changes
These changes look good here. I will pull and poke then call it a day

2021-03-19 21:07 UTC, balarsen requested changes
Ok, this didn't actually work for me.

2021-03-19 21:09 UTC, balarsen commented
I think this would have worked if it was going to...

I checked out this branch and tried to install spacepy from a clean venv and it did not work. 

WSL linux. 

```
git checkout jtniehof-pep518
(python3) ~/git/spacepy$ virtualenv venv
(python3) ~/git/spacepy$ source venv/bin/activate
(venv) (python3) :~/git/spacepy$ pip install .
Processing /mnt/c/Users/234728/git/spacepy
    ERROR: Command errored out with exit status 1:
     command: /mnt/c/Users/234728/git/spacepy/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-eu3g0k72/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-eu3g0k72/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8dcltb7e
         cwd: /tmp/pip-req-build-eu3g0k72/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-eu3g0k72/setup.py", line 36, in <module>
        from numpy.distutils.core import setup
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding file:///mnt/c/Users/234728/git/spacepy. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


```

2021-03-19 21:13 UTC, balarsen commented
from #440 I tried `pip install git+https://github.com/jtniehof/spacepy/@pep518` on that same venv. 

And it did work, so @jtniehof I am happy if you are happy, do you have any knowledge of why `pip install .` is different?

2021-03-19 21:13 UTC, balarsen approved these changes
OK, I am actually happy, I don't understand pip well but no one does.

2021-03-19 21:17 UTC, jtniehof commented
> I think this would have worked if it was going to...
> 
> I checked out this branch and tried to install spacepy from a clean venv and it did not work.

Can you do `pip --version` on this to be sure? It's not going to work on anything but quite new pip, but it does work on my setup.

2021-03-19 21:30 UTC, balarsen commented
> Can you do `pip --version` on this to be sure? It's not going to work on anything but quite new pip, but it does work on my setup.

```
pip --version
pip 21.0.1 from /home/balarsen/tmp/venv/lib/python3.8/site-packages/pip (python 3.8)
```

2021-03-19 21:33 UTC, balarsen commented
OK, scratch my issues. I suspect they were related to what master `jtniehof-pep518` was checkout out on top of. I went totally clean in my repo and it worked. I suspect I was on a balarsen forked master from who knows when.

2021-03-19 21:34 UTC, merged