Two new IMF Calculations: clock angle and epsilon
spacepy/spacepy pull request #732
Opened 2024-03-01 22:29 UTC by spacecataz

This PR adds two new calculations to the Pybats ImfInput object: clock angle and epsilon (solar wind poynting flux scaled by clock angle). It also adds a new test for **all** calculations in the object class.

Unrelated: the use of Matplotlibs `get_cmap` has been removed from `ram.py`. This was throwing deprecation warnings dating back to MPL 3.7 and is not necessary. Tests still pass.

## PR Checklist

- [ x] Pull request has descriptive title
- [x ] Pull request gives overview of changes
- [x ] New code has inline comments where necessary
- [ x] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [ ] Added an entry to release notes if fixing a significant bug or providing a new feature
- [x ] New features and bug fixes should have unit tests
- [ ] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

2024-03-17 20:16 UTC, VascoSch92 commented on spacepy/pybats/__init__.py
> +
```suggestion
```

2024-03-17 20:16 UTC, VascoSch92 commented on spacepy/pybats/__init__.py
> +
```suggestion
```

2024-03-20 21:25 UTC, jtniehof requested changes
This looks good to me...anything else you want to do before merging? Changes to consider to make me happy:

- One typo that's called out separately
- I think this is release note worthy
- Can we put the addedin note on both of the new methods? I know the pybats docs aren't rendering properly right now and are held up by the hypothetical docs overhaul, but it would be good to have that in place for when that _is_ fixed.

2024-03-20 21:25 UTC, jtniehof commented on spacepy/pybats/__init__.py
> +        The resulting value is stored as `self['cloc']` in units of degrees.
Typo, presumably. `self['clock']`

2024-04-23 01:56 UTC, spacecataz commented on spacepy/pybats/__init__.py
> +        The resulting value is stored as `self['cloc']` in units of degrees.
All addressed in latest commits.

2024-04-23 19:41 UTC, jtniehof approved these changes
Looks good; thanks for the changes.

2024-04-23 19:42 UTC, merged