Bump Pandas minimum version for Python 3.9 to 0.25.0
spacepy/spacepy pull request #767
Opened 2024-07-09 18:46 UTC by jamesw732

This pull request resolves #765. The fix was to simply increase the Pandas version for the "oldest" dependency strategy.

## PR Checklist
- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] (N/A) New code has inline comments where necessary
- [X] (N/A) Any new modules, functions or classes have docstrings consistent with SpacePy style
- [X] (N/A) Added an entry to release notes if fixing a significant bug or providing a new feature
- [X] (N/A) New features and bug fixes should have unit tests
- [X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

2024-07-10 17:49 UTC, jtniehof requested changes
We were set up to build pandas from source, so we don't need to rely on a version with binary wheels. We just need one that builds cleanly from source, instead of doing the two-step of "try to build a wheel, fail, run setup.py install". Is there an earlier version than 1.1.3 where that's the case?

2024-07-10 17:49 UTC, jtniehof commented on .github/workflows/ci.yml
> +            piplist: "python-dateutil~=2.5.0 scipy>=1.5.0,<1.6.0 matplotlib~=3.1.0 h5py~=2.10.0 astropy>=2.0,<2.1 pandas>=1.1.3,<1.2.0"
This can just be `pandas~=1.1.3`

2024-07-10 19:27 UTC, jamesw732 commented
> We were set up to build pandas from source, so we don't need to rely on a version with binary wheels. We just need one that builds cleanly from source, instead of doing the two-step of "try to build a wheel, fail, run setup.py install". Is there an earlier version than 1.1.3 where that's the case?

I see, I did not check that. The way I deduced 1.1.3 was by running `pip install pandas==ver` on an otherwise pretty blank conda python 3.9 environment for each version later than 0.24.0, and 1.1.3 was the first that successfully installed. I guess I should just commit/amend and push a bunch of different pandas versions to get the CI to run on each? That might be quicker than figuring out how to install old pandas versions from source locally.

2024-07-10 19:33 UTC, jtniehof commented
> I see, I did not check that. The way I deduced 1.1.3 was by running `pip install pandas==ver` on an otherwise pretty blank conda python 3.9 environment for each version later than 0.24.0, and 1.1.3 was the first that successfully installed. I guess I should just commit/amend and push a bunch of different pandas versions to get the CI to run on each? That might be quicker than figuring out how to install old pandas versions from source locally.

Nope, installing from source locally is pretty easy, just look at the CI. Start with a blank conda env, pip install "cython<3.0", and then go running along your pip install pandas versions. Three possible outcomes:

- build wheel fail, setup.py install works -- current state, bump minor version
- completely fails -- hmm, probably something wrong
- build wheel succeeds and installs --win!

It's pip doing the wheel build and then running setup.py when it fails, nothing you're doing.

2024-07-10 20:57 UTC, jtniehof commented
Pretty sure #749 will fix the 3.12 failure, since that relates to having to build an old numpy to work around f2py. We should probably just wait for that.

2024-07-12 21:19 UTC, jtniehof approved these changes
This only takes two minutes off the build directly, but the pandas wheel builds successfully. So next time the cache expires it should cache the pandas wheel and we'll get a huge speedup.

2024-07-12 21:19 UTC, merged